name: Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
       - example/**

defaults:
  run:
    working-directory: ./
    shell: bash

env:
  REGISTRY: ghcr.io
  ORGANISATION_NAME: philwelz

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    # outputs:
    #   SHA_SHORT: ${{ env.COMMIT_SHORT_SHA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set short git commit SHA
        id: short-sha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
  build:
    name: build
    uses: ./.github/workflows/docker-build.yaml
    needs: [prepare]
    with:
      REGISTRY: ${{ env.REGISTRY }}
      ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
      COMMIT_SHORT_SHA: ${{ env.COMMIT_SHORT_SHA }}
  patch:
    name: patch
    uses: ./.github/workflows/patch-image.yaml
    needs: [prepare,build]
    with:
      REGISTRY: ${{ env.REGISTRY }}
      ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
      COMMIT_SHORT_SHA: ${{ env.COMMIT_SHORT_SHA }}
  sign:
    name: sign
    uses: ./.github/workflows/sign-image.yaml
    needs: [prepare,build,patch]
    with:
      REGISTRY: ${{ env.REGISTRY }}
      ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
      COMMIT_SHORT_SHA: ${{ env.COMMIT_SHORT_SHA }}
    