name: Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
       - example/**

defaults:
  run:
    working-directory: ./
    shell: bash

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    outputs:
      SHA_SHORT: ${{ env.COMMIT_SHORT_SHA }}
    steps:
      - name: Set short git commit SHA
        id: short-sha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
  build:
    name: build
    uses: ./.github/workflows/docker-build.yaml
    with:
      REGISTRY: ghcr.io
      ORGANISATION_NAME: philwelz
      COMMIT_SHORT_SHA: ${{ needs.prepare.outputs.SHA_SHORT }}
  patch:
    name: patch
    uses: ./.github/workflows/patch-image.yaml
    with:
      REGISTRY: ghcr.io
      ORGANISATION_NAME: philwelz
      COMMIT_SHORT_SHA: ${{ needs.prepare.outputs.SHA_SHORT }}