name: Build & Publish to Registry

on:
  workflow_dispatch:
  push:
    paths:
      - 'example/**'
      - '!.github/**'

env:
  REGISTRY: ghcr.io
  ORGANISATION_NAME: philwelz

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        # https://github.com/docker/login-action
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push the fred version of the WebApp
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v5.1.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: true
          sbom: false
          context: ./example
          file: ./example/Dockerfile
          build-args: VERSION_FOLDER=fred-version
          tags: ${{ env.REGISTRY }}/${{ env.ORGANISATION_NAME }}/example:${{ env.COMMIT_SHORT_SHA }}
