name: Build & Publish to Registry

on:
  push:
    branches:
      - master
      - main
      - 'update/*'
      - 'feature/*'

env:
  REGISTRY: ghcr.io
  ORGANISATION_NAME: philwelz
  TAG: ${{ github.sha }}

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        # https://github.com/docker/login-action
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: $GITHUB_TOKEN

      - name: Build and push the fred version of the WebApp
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v5.1.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          context: ./example
          file: ./example/Dockerfile
          build-args: VERSION_FOLDER=fred-version
          tags: ${{ env.REGISTRY }}/${{ env.ORGANISATION_NAME }}/example:${{ env.TAG }}
