name: Patch & Publish to Registry

on:
  workflow_dispatch:
  registry_package:
    types: [published]

env:
  REGISTRY: ghcr.io
  ORGANISATION_NAME: philwelz

jobs:
  patch-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read 
      packages: write # needed for publishing the patched image to the GitHub Container Registry
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Install Cosign
        # https://github.com/sigstore/cosign-installer
        uses: sigstore/cosign-installer@v3.3.0

      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v3.0.0

      - name: Generate Trivy Report
        # https://github.com/aquasecurity/trivy-action/tree/0.16.1
        # Todo versioning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          format: 'json'
          output: 'report.json'
          ignore-unfixed: true
          vuln-type: 'os'
          image-ref: ${{ env.REGISTRY }}/${{ env.ORGANISATION_NAME }}/example:${{ env.COMMIT_SHORT_SHA }}
        # needed for private repos
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}

      - name: Check Vuln Count
        id: vuln_count
        run: |
          report_file="report.json"
          vuln_count=$(jq '.Results | length' "$report_file")
          echo "vuln_count=$vuln_count" >> $GITHUB_OUTPUT

      - name: Copa Action
        if: steps.vuln_count.outputs.vuln_count != '0'
        id: copa
        # https://github.com/project-copacetic/copa-action
        uses: project-copacetic/copa-action@v1.0.1
        with:
          image: ${{ env.REGISTRY }}/${{ env.ORGANISATION_NAME }}/example:${{ env.COMMIT_SHORT_SHA }}
          image-report: 'report.json'
          patched-tag: '${{ env.COMMIT_SHORT_SHA }}-patched'
          # https://github.com/moby/buildkit
          buildkit-version: 'v0.12.4'
          # https://github.com/project-copacetic/copacetic
          copa-version: '0.6.0'

      - name: Login to GitHub Container Registry
        if: steps.copa.conclusion == 'success'
        id: login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker Push Patched Image
        if: steps.login.conclusion == 'success'
        id: push
        run: |
          docker push ${{ steps.copa.outputs.patched-image }}

      - name: Docker get image digest
        if: steps.login.conclusion == 'success'
        id: image
        run: |
          apt-get update && apt-get install -y jq
          echo "digest=$(docker image inspect ${{ steps.copa.outputs.patched-image }} | jq -r '.[0].RepoDigests[0]')" >> $GITHUB_OUTPUT

      - name: Cosign sign the image with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.image.outputs.digest }}
          TAG: ${{ steps.copa.outputs.patched-image }}
        run: |
          cosign sign --yes ${TAG}@${DIGEST}

      # - name: Cosign sign the image with GitHub OIDC Token
      #   env:
      #     DIGEST: ${{ steps.push.outputs.digest }}
      #     TAG: ${{ steps.copa.outputs.patched-image }}
      #   run: |
      #     cosign attach sbom --sbom latest.spdx ${TAG}@${DIGEST}

