name: Build & Publish to Registry

on:
  workflow_call:
    inputs:
      ### Values from CICD Workflow ###
      REGISTRY:
        required: true
        type: string
        description: 'The Environemnt which should be used.'
      ORGANISATION_NAME:
        type: string
        required: true
        description: 'The Subscription ID which should be used.'
      COMMIT_SHORT_SHA:
        type: string
        required: true
        description: 'The Subscription ID which should be used.'

jobs:
  patch-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read 
      packages: write # needed for publishing the patched image to the GitHub Container Registry
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - name: Install Cosign
        # https://github.com/sigstore/cosign-installer
        uses: sigstore/cosign-installer@v3.3.0

      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v3.0.0

      - name: Generate Trivy Report
        # https://github.com/aquasecurity/trivy-action/tree/0.16.1
        # Todo versioning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          format: 'json'
          output: 'report.json'
          ignore-unfixed: true
          vuln-type: 'os'
          image-ref: ${{ inputs.REGISTRY }}/${{ inputs.ORGANISATION_NAME }}/example:${{ inputs.COMMIT_SHORT_SHA }}
        # needed for private repos
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}

      - name: Check Vuln Count
        id: vuln_count
        run: |
          report_file="report.json"
          vuln_count=$(jq '.Results | length' "$report_file")
          echo "vuln_count=$vuln_count" >> $GITHUB_OUTPUT

      - name: Copa Action
        if: steps.vuln_count.outputs.vuln_count != '0'
        id: copa
        # https://github.com/project-copacetic/copa-action
        uses: project-copacetic/copa-action@v1.0.1
        with:
          image: ${{ inputs.REGISTRY }}/${{ inputs.ORGANISATION_NAME }}/example:${{ inputs.COMMIT_SHORT_SHA }}
          image-report: 'report.json'
          patched-tag: '${{ inputs.COMMIT_SHORT_SHA }}-patched'
          # https://github.com/moby/buildkit
          buildkit-version: 'v0.12.4'
          # https://github.com/project-copacetic/copacetic
          copa-version: '0.6.0'

      - name: Login to GitHub Container Registry
        if: steps.copa.conclusion == 'success'
        id: login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker Push Patched Image
        if: steps.login.conclusion == 'success'
        id: push
        run: |
          docker push ${{ steps.copa.outputs.patched-image }}

      # - name: Cosign sign the image with GitHub OIDC Token
      #   env:
      #     DIGEST: ${{ steps.push.outputs.digest }}
      #     TAG: ${{ steps.copa.outputs.patched-image }}
      #   run: |
      #     cosign attach sbom --sbom latest.spdx ${TAG}@${DIGEST}

